% Clear Command Window
clc;


% Print a blank line
fprintf("\n");


% Print an introductory message on the choice of
% the stance towards the notion of realism
% I find most appealing
fprintf("From the three main stances towards the notion of\n" + ...
        "realism that capture the usual way we deal with\n" + ...
        "the <strong>Bell - Clauser-Horne-Shimony-Holt</strong> " + ...
        "<strong>(Bell-CHSH)</strong>\n" + ...
        "and <strong>Kochen-Specker (KS)</strong> " + ...
        "<strong>no-go theorems</strong>,\n" + ...
        "the one I find most appealing is:\n");

% Print a blank line
fprintf("\n");

% Print the information and description about
% the Freeze stance for the realism notion,
% as the one I find most appealing
fprintf(" <strong>* Freeze (Medium Realism):</strong>\n");
fprintf("    => ""I believe in a notion of 'modern realism',\n" + ...
        "        which is not captured by the ontological model\n" + ...
        "        framework and, as such, manages to sidestep\n" + ...
        "        the implications of the typical no-go theorems"";\n");

% Print a blank line
fprintf("\n");


% Print an introductory message on
% the justification for the choice of
% the stance towards the notion of
% realism I find most appealing
fprintf("The justification is:\n");

% Print a blank line
fprintf("\n");

% Print the justification for the choice of the stance
% towards the notion of realism I find most appealing
fprintf(" * I strongly believe on the idea of intedeterminism and\n" + ...
        "   unpredictability derived from the probabilistic nature\n" + ...
        "   from Quantum Mechanics, as well as I also believe that\n" + ...
        "   the observer actor plays an essential role on the several\n" + ...
        "   interactions with the physical systems and their respective\n" + ...
        "   quantum phenomena. I also believe on the notions of both\n" + ...
        "   Bohr's Complementarity Principle and Heisenberg's Uncertainty\n" + ... 
        "   Principles, where the quantum properties of a particle and\n" + ... 
        "   a wave (e.g., the position and momentum of a particle) cannot\n" + ...
        "   be computed and determined simulaneously by an observer actor.\n" + ...
        "   Finally, I agree that most of these properties can be verified\n" + ...
        "   on a specialized laboratory with proper quantum devices,\n" + ...
        "   following an instrumentalist approach, from which we\n" + ...
        "   can validade the usefulness of theory for predicting\n" + ...
        "   some experimental results on practice, rather than\n" + ...
        "   deeply describing the underlying reality;\n");


% Print two blank lines
fprintf("\n\n");

% Print a separator
fprintf("***********************************" + ...
        "***********************************");

% Print two blank lines
fprintf("\n\n");


% Print a blank line
fprintf("\n");


% Print an introductory message about the concrete interpretation of
% the two no-go theorems for my choice on the stance towards
% the notion of realism I find most appealing
fprintf("As a concrete interpretation of" + ...
        "the two <strong>no-go theorems</strong>\n" + ...
        "(<strong>Bell - Clauser-Horne-Shimony-Holt</strong> " + ...
        "<strong>(Bell-CHSH)</strong> and\n" + ...
        "<strong>Kochen-Specker (KS)</strong> " + ...
        "<strong>no-go theorems</strong>) for my choice on\n" + ...
        "the stance towards the notion of realism I find most\n" + ...
        "appealing, is the following one:\n");

% Print a blank line
fprintf("\n");


% Print the information and description
% about the conjunction of conditions for
% the Bell - Clauser-Horne-Shimony-Holt (Bell-CHSH) no-go theorem
fprintf(" <strong>1) Bell - Clauser-Horne-Shimony-Holt (Bell-CHSH):</strong>\n");
fprintf("    * <strong>Parameter Independence (PI) ∧ Outcome Independence (OI) ∧\n" + ...
        "      Measurement Independence (MI) ∧ Quantum Mechanics (QM)\n" + ...
        "      => Contradiction!</strong>\n");

% Print a blank line
fprintf("\n");


% Print a message about the concrete interpretation of
% the Bell - Clauser-Horne-Shimony-Holt (Bell-CHSH)
% no-go theorem for my choice on the stance towards
% the notion of realism I find most appealing
fprintf("      => For this no-go theorem, I believe that both\n" + ...
        "         the parameters and outcomes of a physical experiment\n" + ...
        "         are not independent and can affect the final results of\n" + ...
        "         that same experiment, depending on the configured setup\n" + ...
        "         we choose a priori, dropping then both conditions of\n" + ...
        "         <strong>Parameter Independence (PI)</strong> and " + ...
                 "<strong>Outcome Independence (OI)</strong>.\n" + ...
        "         However, I strongly belive that each observer actor\n" + ...
        "         plays an essential role in its interaction with\n" + ...
        "         a physical experiment, and have a free-will to\n" + ...
        "         choose the measurement configuration independently\n" + ...
        "         from all the others chosen by all the remaining\n" + ...
        "         involved observer actors, " + ...
                 "<strong>not</strong> dropping then\n" + ...
        "         the condition of <strong>Measurement Independence</strong> " + ...
                 "<strong>(MI)</strong>;\n")


% Print a blank line
fprintf("\n");


% Print the information and description
% about the conjunction of conditions for
% the Kochen - Specker (KS) no-go theorem
fprintf(" <strong>2) Kochen - Specker (KS):</strong>\n");
fprintf("    * <strong>Outcome Determinism (OD) ∧ \n" + ...
        "      Measurement Non-Contextuality (MNC) ∧\n" + ...
        "      Quantum Mechanics (QM) => Contradiction!</strong>\n");

% Print a blank line
fprintf("\n");


% Print a message about the concrete interpretation of
% the Kochen - Specker (KS) no-go theorem for my choice on
% the stance towards the notion of realism I find most appealing
fprintf("      => For this no-go theorem, I believe that\n" + ...
        "         the outcomes of a physical experiment can be\n" + ...
        "         undeterministic, depending on the configured\n" + ...
        "         setup of that physical experiment, the actions\n" + ...
        "         a possible observer actor make on that same\n" + ...
        "         physical system, the possible interactions that\n" + ...
        "         physical system can have with the environment,\n" + ...
        "         among many factors, affecting its outcome results,\n" + ...
        "         dropping then the condition of " + ...
                 "<strong>Outcome Determinism (OD)</strong>.\n" + ...
        "         On the other hand, I believe that the measurements\n" + ...
        "         are usually defined and performed considering\n" + ...
        "         a global context for the physical experiment,\n" + ...
        "         depending on the configured setup we choose for that\n" + ...
        "         physical experiment, which can affect the values of\n" + ...
        "         the quantum properties being measured and their\n" + ...
        "         respective final outcome results, dropping then\n" + ...
        "         the condition of <strong>Measurement</strong> " + ...
                 "<strong>Non-Contextuality (MNC)</strong>.\n");


% Print two blank lines
fprintf("\n\n");

% Print a separator
fprintf("***************************************" + ...
        "***************************************");

% Print two blank lines
fprintf("\n\n");


% Print blank line
fprintf("\n")