% Clear Command Window
clc;


% Print a blank line
fprintf("\n");

% Print the headline for the three
% main stances for the realism notion
fprintf("The three main stances towards realism are:\n");

% Print the information and description about
% the Fight stance for the realism notion
fprintf(" <strong>1) Fight (Strong Realism):</strong>\n");
fprintf("    * ""I believe in old-fashioned realism,\n" + ...
        "       and as such any putative ontology of\n" + ...
        "       this kind is cornered by the usual\n" + ...
        "       no-go theorems. Consequently, at least one of\n" + ...
        "       the assumptions of the considered no-go theorem,\n" + ...
        "       such as Bell - Clauser-Horne-Shimony-Holt (Bell-CHSH)\n" + ...
        "       or Kochen-Specker (KS) needs to be dropped"";\n");

% Print a blank line
fprintf("\n");

% Print the information and justification about
% the choice of interpretation of Quantum Mechanics
% for the Fight stance for the realism notion
fprintf("    * A possible Quantum Mechanics Interpretation that\n" + ...
        "      fits on the <strong>Fight</strong> stance " + ...
              "is the <strong>De Broglie-Bohm</strong>\n" + ...
        "      <strong>Interpretation (Bohmian Interpretation)</strong>, since:\n");
fprintf("      i)   Proposes a strong ontological realism,\n" + ...
        "           where the particles always have a well-defined\n" + ...
        "           position, momentum, and state, independently of\n" + ...
        "           being observed or not;\n");
fprintf("      ii)  Accepts local hidden variables that allow to\n" + ...
        "           explain the position, momentum, or state of\n" + ...
        "           a particle without requiring a notion of\n" + ... 
        "           wave-function collapse;\n");
fprintf("      iii) Have a deterministic nature, where all\n" + ...
        "           the future quantum behaviour of a physical system\n" + ...
        "           is completely determined, given its initial state;\n");
fprintf("      iv)  (Try to) have causal explanations for all\n" + ...
        "           the quantum phenomena, using notions of\n" + ...
        "           quantum potential and pilot wave theory to\n" + ...
        "           explain quantum phenomena such as non-locality\n" + ...
        "           and wave interference, for example.\n")


% Print two blank lines
fprintf("\n\n");

% Print a separator
fprintf("***********************************" + ...
        "***********************************");

% Print two blank lines
fprintf("\n\n");


% Print the information and description about
% the Freeze stance for the realism notion
fprintf(" <strong>2) Freeze (Medium Realism):</strong>\n");
fprintf("    * ""I believe in a notion of 'modern realism',\n" + ...
        "       which is not captured by the ontological model\n" + ...
        "       framework and, as such, manages to sidestep\n" + ...
        "       the implications of the typical no-go theorems"";\n");

% Print a blank line
fprintf("\n");

% Print the information and justification about
% the choice of interpretation of Quantum Mechanics
% for the Freeze stance for the realism notion
fprintf("    * A possible Quantum Mechanics Interpretation that fits on\n" + ...
        "      the <strong>Freeze</strong> stance " + ...
              "is the <strong>Copenhagen Interpretation</strong>, since:\n");
fprintf("      i)   Follows the idea of indeterminism, since it\n" + ...
        "           accepts the Heisenberg's Uncertainty Principle\n" + ...
        "           as a fundamental and irreversible characteristic of\n" + ...
        "           quantum phenomena, where a particle can never\n" + ...
        "           have its position and momentum well-defined and\n" + ...
        "           determined simultaneously, for example;\n");
fprintf("      ii)  Has the observer playing a primary and central\n" + ...
        "           role, where the wave-function (probabilistically)\n" + ...
        "           represents our knowledge or information about\n" + ...
        "           the quantum properties of a physical system,\n" + ... 
        "           avoiding and holding a deterministic explanation of\n" + ...
        "           quantum events and reality itself until the moment of\n" + ...
        "           an observation, focusing instead on the interaction\n" + ...
        "           between an observer and a physical system;\n");
fprintf("      iii) Accepts the notion of wave-function collapse as\n" + ...
        "           a fundamental postulate, during a quantum measurement,\n" + ...
        "           leading to a single outcome among the several ones\n" + ...
        "           described by the wave-function before that same\n" + ...
        "           quantum measurement happens, without seeking a deeper\n" + ...
        "           explanation for the underlying mechanism or process;\n");
fprintf("      iv)  Follows the principle of Bohr's Complementarity\n" + ...
        "           Principle, also interconnected with the Heisenberg's\n" + ...
        "           Uncertainty Principle, where the quantum properties of\n" + ...
        "           a particle and a wave cannot be computed and determined\n" + .....
        "           simulaneously by an observer actor, being complementary\n" + ...
        "           aspects of a physical system;\n");
fprintf("      v)   Settles on an instrumentalist approach,\n" + ...
        "           emphasizing the practical usefulness of theory\n" + ...
        "           for predicting experimental results rather than\n" + ...
        "           describing the underlying reality, avoiding\n" + ...
        "           deep philosophical aspects.\n");


% Print two blank lines
fprintf("\n\n");

% Print a separator
fprintf("***********************************" + ...
        "***********************************");

% Print two blank lines
fprintf("\n\n");


% Print the information and description about
% the Flight stance for the realism notion
fprintf(" <strong>3) Flight (No/Weak Realism):</strong>\n");
fprintf("    * ""I do not believe in any notion of realism"";\n");

% Print a blank line
fprintf("\n");

% Print the information and justification about
% the choice of interpretation of Quantum Mechanics
% for the Flight stance for the realism notion
fprintf("    * A possible Quantum Mechanics Interpretation that fits on\n" + ...
        "      the <strong>Flight</strong> stance " + ...
              "is the <strong>Many World Interpretation</strong>, since:\n");
fprintf("      i)   Avoids the notion of wave-function collapse,\n" + ...
        "           postulating that every possible outcome or\n" + ...
        "           reality resulting from a quantum measurement on\n" + ...
        "           a physical system really occur, but in different\n" + ...
        "           and parallel branches of reality/universe;\n");
fprintf("      ii)  Accepts the idea of multiplicity of universes,\n" + ...
        "           where every quantum event results on dividing\n" + ...
        "           the universe into a large number of branches,\n" + ...
        "           avoiding explanations about the uniqueness of\n" + ...
        "           observed quantum events, rather than trying to\n" + ...
        "           reconcile the wave function with a single observed\n" + ...
        "           reality, allowing all possible realities to exist\n" + ...
        "           simultaneously in separate universes;\n");
fprintf("      iii) Avoids classical philosophical problems of\n" + ...
        "           quantum mechanics, such as the role of the observer\n" + ...
        "           and the nature of objective reality, circumventing\n" + ...
        "           the need for a special observer actor or\n" + ...
        "           a wave-function collapse mechanism;\n");
fprintf("      iv)  Reinterprets the traditional comprehension of\n" + ...
        "           the probabilistic and undeterministic nature of\n" + ...
        "           quantum measurements, redefining the respective\n" + ...
        "           probabilities as a distribution measure of\n" + ...
        "           many outcomes and realities;\n");
fprintf("      v)   Rejects the idea of classical realism,\n" + ...
        "           departing from the classical conception of\n" + ...
        "           a single reality objective and shared universe,\n" + ...
        "           while embraces the idea of multiple universes,\n" + ...
        "           in favor of a more complex and ramified reality,\n" + ...
        "           avoiding to reconcile quantum mechanics\n" + ...
        "           with a traditional view of reality;\n")


% Print two blank lines
fprintf("\n\n");

% Print a separator
fprintf("***********************************" + ...
        "***********************************");

% Print two blank lines
fprintf("\n\n");


% Print a blank line
fprintf("\n");